//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSerach_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRegTB
    {
        public int Company_Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Address { get; set; }
        public string Company_Email { get; set; }
        public string Website_Address { get; set; }
        public long Phone { get; set; }
    }
}
