//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSerach_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_JobAdd_TB
    {
        public int Job_Id { get; set; }
        public int Company_Id { get; set; }
        public string Job_Title { get; set; }
        public string Job_Description { get; set; }
        public string Job_Skills { get; set; }
        public int Jobexp_Year { get; set; }
        public string Min_Qulification { get; set; }
        public string Job_Status { get; set; }
        public System.DateTime Job_EndDate { get; set; }
    }
}
